### ISSUE TITLE
Update code to use drainage area sqmi property

### ISSUE THREAD

**Issue by jdkleiner** [HARPgroup/r-dh-ecohydro#25]
Need to utilize the already imported "nhdp_drainage_sqmi" property to eliminate clunky unit conversions between sqkm and sqmi

**Comment by jdkleiner** [comment]
Code updates have been pushed to jdkleiner branch

**Comment by jdkleiner** [comment]
Jdkleiner branch merged with master

**Comment by jenniferRapp** [comment]
How does this affect the stored figures on VAhydro?  Will we have to re-run them so that the query by square miles retrieves the files?
