### ISSUE TITLE
Ecoiii-HUC6 Potomac Ridge and Valley missing 

### ISSUE THREAD

**Issue by jenniferRapp** [HARPgroup/r-dh-ecohydro#32]
I'm working with the dashboard to view the ELF plots of the Ecoiii-HUC6 PW regressions and noticed that there is not one for Ridge and Valley - Potomac for MAF or DA.  There are HUC8 ELFs for NF and SF Shenandoah so I expect we can run the ELF for the ECO-huc6 for that ecoregion.

**Comment by rburghol** [comment]
I am not certain when we last ran the eco-huc6 data, so not entirely surprised that it is not in there right now, though the fact that there is 3 other Potomac regions suggests that it failed to be able to calculate one for that region. Would you be able to try to run that one?

**Comment by jenniferRapp** [comment]
Yes I will run it.



*Jennifer Lynn Rapp, Biogeographer and GIS Specialist*
jrapp@usgs.gov
U.S. Geological Survey
Virginia and West Virginia Water Science Center
1730 East Parham Road
Richmond, VA 23228
w. 804-261-2635

**Comment by jdkleiner** [comment]
The Ridge and Valley - Potomac feature appears to have faulty geometry, I'm looking into it. I don't think it's a simple issue of this one not being run.

**Comment by jenniferRapp** [comment]
When I ran it it said it found no features.  It worked fine for Northern Piedmont-Potomac.

**Comment by jenniferRapp** [comment]
Any progress on this issue with the geometry?

**Comment by rburghol** [comment]
I just checked the system and it looks like the geometry has been fixed, or at least our basic system queries work - see below - can you try to the ELF analysis again and report back?
![image](https://user-images.githubusercontent.com/4571170/36051809-5a015c88-0db9-11e8-9463-e2488c976a8f.png)

**Comment by rburghol** [comment]
Just a note - since it is largely in West Virginia, it might not have enough locations?

**Comment by jenniferRapp** [comment]
I'll look at it again.  The North and South Forks have enough data for Huc8 ELFs so I expected there would be enough for the larger region.

**Comment by jdkleiner** [comment]
I believe I fixed this faulty geometry a couple weeks ago. Just tested by running the code for Ridge and Valley - Potomac, ran without issue.
