### ISSUE TITLE
PWIT Equation - need to take log(x)

### ISSUE THREAD

**Issue by passeroe** [HARPgroup/r-dh-ecohydro#34]
During breakpoint calculations where we use the lm() function to find piecewise regressions, we need to take the log(x). We use log(x) for our upper quantile calculations and plot on a semi-log scale. Since we are assuming this data is logarithmic, we need to transform the x-values to be able to find a meaningful piecewise linear regression. 

This is the change I propose making. I've already tested it, and the code works fine. It improved r^2 values and increased breakpoint estimates in the two datasets I was able to look at.

`for(n in 1:length(breaks)){
        piecewise1 <- lm(y ~ log(x)*(x < breaks[n]) + log(x)*(x >= breaks[n]))
        mse[n] <- summary(piecewise1)[6]
      }`

**Comment by jenniferRapp** [comment]
I know the code was updated today.  I pulled it and updated my system.  For some reason it is not creating the pw-it graphs and storing them locally.  It is creating quantreg, ymax, and pw_it_RS.  

Question, did you also update pw_it_RS?

**Comment by passeroe** [comment]
I also updated pw_it_RS.
